console.log("sample.js: begin runtime mutation checks");
document.title = "Sample Layout Playground (external)";
document.body.style.background = "#e6ffed";
document.getElementById("hero-title").innerText = "Sample Layout Playground (runtime)";
document.querySelector("#hero-title").style.color = "#dc2626";
document.querySelector("#hero-title").style.fontSize = "32px";
document.getElementById("js-message").innerText = "Runtime update: getElementById + innerText is active.";
document.querySelector("#js-target-card").style.background = "#fde68a";
document.querySelector("#js-target-card").style.backgroundColor = "#fde68a";
document.querySelector("#js-target-card").style.borderColor = "#f97316";
document.getElementById("js-target-card").style.borderWidth = "5px";
document.querySelector("#transparent-fixture").style.backgroundColor = "transparent";
document.querySelector("#status-chip").style.backgroundColor = "#bfdbfe";
document.querySelector("#status-chip").style = "background-color: #86efac; border-color: #22c55e; color: #14532d;";
document.getElementById("status-chip").textContent = "Runtime chip: JS textContent alias + borderColor mutation is active.";
console.log("sample.js: updated title, body background, and runtime style-targeted nodes");
document.body.style = "background-color: #e6ffed; color: #1f2937;";
document.body.className = "page body-runtime-armed";
document.body.setAttribute("class", "page body-runtime-armed body-setattr-runtime");
document.body.setAttribute("data-body-setattr-fixture", "armed");
document.body.removeAttribute("data-body-removeattr-fixture");
document.body.id = "page-shell-armed";
document.getElementById("setattr-style-fixture").setAttribute("style", "background-color: #d9f99d; border-color: #65a30d; color: #365314;");
document.getElementById("setattr-nonstyle-fixture").setAttribute("class", "setattr-nonstyle-fixture armed");
document.getElementById("setattr-nonstyle-fixture").setAttribute("title", "Runtime setAttribute class mutation is active.");
document.getElementById("setattr-id-fixture").setAttribute("title", "Runtime setAttribute(\"id\") mutation is active.");
document.getElementById("setattr-id-fixture").setAttribute("id", "setattr-id-fixture-armed");
document.getElementById("runtime-classname-fixture").className = "fixture runtime-classname-fixture classname-armed";
document.getElementById("runtime-classname-fixture").setAttribute("title", "Runtime className mutation is active.");
document.getElementById("removeattr-style-fixture").removeAttribute("style");
document.getElementById("removeattr-style-fixture").setAttribute("title", "Runtime removeAttribute(\"style\") mutation is active.");
document.querySelector("#removeattr-class-fixture").removeAttribute("class");
document.getElementById("removeattr-class-fixture").setAttribute("title", "Runtime removeAttribute(\"class\") mutation is active.");
document.getElementById("runtime-id-fixture").id = "runtime-id-fixture-armed";
