#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export CODEX_ESTATE_AUTOGIT="${CODEX_ESTATE_AUTOGIT:-1}"
export CODEX_ESTATE_PUSH="${CODEX_ESTATE_PUSH:-1}"
export CODEX_ESTATE_CREATE_PR="${CODEX_ESTATE_CREATE_PR:-1}"
export CODEX_ESTATE_WAIT_FOR_CI="${CODEX_ESTATE_WAIT_FOR_CI:-1}"
export CODEX_ESTATE_CI_AUTOFIX="${CODEX_ESTATE_CI_AUTOFIX:-1}"
export CODEX_ALLOW_KNOWN_BASELINE_FAILURES="${CODEX_ALLOW_KNOWN_BASELINE_FAILURES:-1}"

exec bash "$SCRIPT_DIR/resume-live.sh" "$@"
